### PR TITLE
Rename requests.http to requests.md

### PR DESCRIPTION
**Pull request by AmraniCh**

### CODE REVIEW

**Comment by Ahmard** [comment]
Why do we need to rename it?

**Comment by AmraniCh** [comment]
I was thinking that the syntax of `requests.http` file is markdown.

**Comment by Ahmard** [comment]
No, it's requests file.
Check this out: https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html

**Comment by AmraniCh** [comment]
Ehmm, thanks for the info.

**Pull request closed without merging**
